import java.time.Duration

/*
* This file was generated by the Gradle 'init' task.
*
* This generated file contains a sample Java library project to get you started.
* For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
*/

// ====================================== PLUGINS =============================
plugins {
    `java-library`
    id("com.diffplug.spotless") version "6.25.0"
    `maven-publish`
    signing
    id("com.gradleup.nmcp") version "1.5.0"

}
// ============================================================================

configurations {
    create("jaxws")
}

// ============================== SPOTLESS =====================================
spotless {
    java {
        target("src/**/*.java")
        targetExclude("build/**/*.java")
        targetExclude("src/test/**/*.java")
        licenseHeader(
            """// SPDX-License-Identifier: Apache-2.0
            // Copyright (c) 2026 Nulldoomer

            """
        )
        removeUnusedImports()
        googleJavaFormat()
    }
}
// ============================================================================

// ================================ VERSIONS ===================================
group = "io.github.nulldoomer"
version = "1.2.2"
// ============================================================================

val artifactName = "opensri"

val signingKey = providers.gradleProperty("signingKey")
    .orElse(providers.gradleProperty("signing.key"))
val signingPassword = providers.gradleProperty("signingPassword")
    .orElse(providers.gradleProperty("signing.password"))
val mavenCentralUsername = providers.gradleProperty("mavenCentralUsername")
val mavenCentralPassword = providers.gradleProperty("mavenCentralPassword")

// ============================= RELEASE TASKS =================================
java {
    withSourcesJar()
    withJavadocJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.getByName<Jar>("jar") {
    archiveBaseName.set(artifactName)
}
// ============================================================================

// =========================== SIGNING =========================================
signing {
    isRequired = gradle.taskGraph.allTasks.any {
        it.name.contains("CentralPortal") || it.name.startsWith("sign")
    }
    useInMemoryPgpKeys(signingKey.orNull, signingPassword.orNull)
    sign(publishing.publications)
}
// ============================================================================

// ====================== MAVEN CENTRAL PUBLISHING ============================
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])

            groupId = "io.github.nulldoomer"
            artifactId = artifactName

            pom {
                name.set("OpenSRI")
                description.set(
                    """
                    Esta iniciativa surge de mi experiencia al implementar por primera vez
                    un sistema de facturación electrónica. Durante el proceso encontré
                    documentación dispersa, referencias inconsistentes y una gran cantidad
                    de material desactualizado enfocado en tecnologías heredadas.
                    Además, muchas de las soluciones disponibles se basan en servicios de
                    terceros bajo modelos de suscripción, lo que puede representar una barrera
                    para desarrolladores independientes y pequeñas empresas. Como respuesta
                    a estas dificultades, decidí crear una alternativa abierta que facilite la
                    integración de facturación electrónica y reduzca el tiempo necesario
                    para comprender e implementar los requerimientos del SRI.
                """.trimIndent()
                )
                url.set("https://github.com/nulldoomer/Open-SRI")

                licenses {
                    license {
                        name.set("Apache License, Version 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }

                developers {
                    developer {
                        id.set("nulldoomer")
                        name.set("Paulo Yépez")
                    }
                }

                scm {
                    connection.set("scm:git:https://github.com/nulldoomer/Open-SRI.git")
                    developerConnection.set("scm:git:ssh://git@github.com/nulldoomer/Open-SRI.git")
                    url.set("https://github.com/nulldoomer/Open-SRI")
                }
            }
        }
    }
}


// ============================================================================

// ====================== CENTRAL PORTAL DEPLOYMENT ============================
nmcp {
    publishAllPublicationsToCentralPortal {
        username.set(mavenCentralUsername)
        password.set(mavenCentralPassword)
        publishingType.set("USER_MANAGED")
        publicationName.set("${project.name}-${project.version}")
        validationTimeout.set(Duration.ofMinutes(10))
        publishingTimeout.set(Duration.ofMinutes(10))
    }
}
// ============================================================================

// ========================== DEPENDENCIES =====================================
repositories {
    mavenCentral()
}

dependencies {
    // Logging API only (no implementation)
    api("org.slf4j:slf4j-api:2.0.13")

    // Testing
    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("net.jqwik:jqwik:1.8.4")
    testImplementation("org.mockito:mockito-core:5.11.0")

    // XML serialization
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.0")
    runtimeOnly("org.glassfish.jaxb:jaxb-runtime:4.0.0")

    // Firma XAdES
    implementation("com.googlecode.xades4j:xades4j:2.4.0")

    // Web Service
    implementation("jakarta.xml.ws:jakarta.xml.ws-api:4.0.1")
    runtimeOnly("com.sun.xml.ws:jaxws-rt:4.0.2")

    // Tool Config
    "jaxws"("com.sun.xml.ws:jaxws-tools:4.0.2")
}
// ============================================================================

// ============================== TEST PLATFORM ================================
tasks.named<Test>("test") {
    useJUnitPlatform()
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}
// ============================================================================

// =========================== TEST RESOURCES ==================================
val generateTestCertificate by tasks.registering(Exec::class) {
    group = "verification"
    description = "Generates a dummy PKCS12 certificate for testing if it does not exist."

    val certFile = file("src/test/resources/test-firma.p12")
    onlyIf { !certFile.exists() }

    doFirst {
        certFile.parentFile.mkdirs()
    }

    commandLine(
        "keytool", "-genkeypair",
        "-alias", "sri-test-firma",
        "-keyalg", "RSA",
        "-keysize", "2048",
        "-storetype", "PKCS12",
        "-keystore", certFile.absolutePath,
        "-storepass", "password",
        "-keypass", "password",
        "-dname", "CN=SRI Test Firma, O=OpenSRI, C=EC",
        "-validity", "365"
    )
}

tasks.named("processTestResources") {
    dependsOn(generateTestCertificate)
}

tasks.named("test") {
    dependsOn(generateTestCertificate)
}
// ============================================================================
