/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

// ====================================== PLUGINS =============================
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    java
    id("com.diffplug.spotless") version "6.25.0"
}

spotless {
    java {
        target("src/**/*.java")
        targetExclude("build/**/*.java")
        targetExclude("src/test/**/*.java")
        licenseHeader(
            """// SPDX-License-Identifier: Apache-2.0
            // Copyright (c) 2026 Nulldoomer

            """
        )

        removeUnusedImports()
        googleJavaFormat()
    }
}

// ====================================== PLUGINS =============================
group = "io.github.opensri"
version = "0.1.0-SNAPSHOT"


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Logging API only (no implementation)
    api("org.slf4j:slf4j-api:2.0.13")

    // Testing
    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("net.jqwik:jqwik:1.8.4")
    testImplementation("org.mockito:mockito-core:5.11.0")

    // XML serialization
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.0")
    runtimeOnly("org.glassfish.jaxb:jaxb-runtime:4.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
