spring:
  application:
    name: playground-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PWD}
      timeout: 2000ms        # Formato correcto para duración
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 200ms

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG

rate-limit:
  enabled: true
  capacity: 10
  refill-period: 60000ms
  idle-expiry: 10000ms
  max-clients: 100000