name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdk/sri-sdk-java

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sdk/sri-sdk-java/build/libs/*.jar
          generate_release_notes: true

# TODO: Add step to check the gradle version to ensure it's the same as the github tag version, to keep the build sync.